#!/bin/bash
sips -Z 1024 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-1024.png
sips -Z 120 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-120.png
sips -Z 128 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-128.png
sips -Z 1280 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-1280.png
sips -Z 144 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-144.png
sips -Z 152 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-152.png
sips -Z 16 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-16.png
sips -Z 167 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-167.png
sips -Z 180 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-180.png
sips -Z 192 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-192.png
sips -Z 1920 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-1920.png
sips -Z 20 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-20.png
sips -Z 256 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-256.png
sips -Z 29 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-29.png
sips -Z 32 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-32.png
sips -Z 40 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-40.png
sips -Z 48 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-48.png
sips -Z 512 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-512.png
sips -Z 58 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-58.png
sips -Z 60 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-60.png
sips -Z 64 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-64.png
sips -Z 640 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-640.png
sips -Z 72 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-72.png
sips -Z 76 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-76.png
sips -Z 80 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-80.png
sips -Z 87 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-87.png
sips -Z 96 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-96.png
sips -Z 108 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-adaptive-108.png
sips -Z 162 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-adaptive-162.png
sips -Z 216 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-adaptive-216.png
sips -Z 324 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-adaptive-324.png
sips -Z 432 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-adaptive-432.png
sips -Z 144 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-round-144.png
sips -Z 192 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-round-192.png
sips -Z 48 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-round-48.png
sips -Z 72 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-round-72.png
sips -Z 96 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-round-96.png
sips -Z 1280 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-1280.png
sips -Z 144 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-144.png
sips -Z 192 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-192.png
sips -Z 320 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-320.png
sips -Z 48 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-48.png
sips -Z 480 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-480.png
sips -Z 640 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-640.png
sips -Z 72 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-72.png
sips -Z 96 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-96.png
sips -Z 960 src/zakat_tracker/resources/zakat_tracker_white_4096.png --out icons/zakat_tracker-square-960.png